# Generated by Django 3.1.3 on 2020-12-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20201126_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbank',
            old_name='chapter',
            new_name='bt',
        ),
        migrations.RenameField(
            model_name='questionbank',
            old_name='difficulty',
            new_name='co',
        ),
    ]
