# Generated by Django 3.1.4 on 2021-01-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_questionbank_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='flag',
        ),
    ]
