# Generated by Django 3.1.3 on 2020-12-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20201218_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='sem',
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='co',
            field=models.CharField(max_length=100),
        ),
    ]
